# CREAETING THE AUGMENTED DATASET

In [15]:
!rm -r venv_txtatck
!python3.7 -m venv venv_txtatck
!pip install textattack

  Using cached textattack-0.3.8-py3-none-any.whl (418 kB)
  Using cached num2words-0.5.12-py3-none-any.whl (125 kB)
  Using cached pycld2-0.41-cp37-cp37m-linux_x86_64.whl
  Using cached more_itertools-9.1.0-py3-none-any.whl (54 kB)
  Using cached lru_dict-1.1.8-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26 kB)
  Using cached filelock-3.11.0-py3-none-any.whl (10.0 kB)
  Using cached jieba-0.42.1-py3-none-any.whl
  Using cached scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
  Using cached flair-0.12.2-py3-none-any.whl (373 kB)
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
  Using cached terminaltables-3.1.10-py2.py3-none-any.whl (15 kB)
  Using cached word2number-1.1-py3-none-any.whl
  Using cached lemminflect-0.2.3-py3-none-any.whl (769 kB)
  Using cached bert_score-0.3.13-py3-none-any.whl (61 kB)
  Using cached pinyin-0.4.0-py3-none-any.whl
  Using cached numpy-1.21.6-cp37-cp37m-manylinux_2_12

In [16]:
from textattack.augmentation.recipes import EasyDataAugmenter
easyAugmenter = EasyDataAugmenter(pct_words_to_swap=0.5, transformations_per_example=1)

[nltk_data] Downloading package omw-1.4 to /home/maxwell/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [17]:
import pandas as pd
import numpy as np

In [22]:
data = pd.read_csv("Sentiment_Dataset/Sentiment140/Clean/sentiment140.csv", encoding='utf-8')
data = data.iloc[0:50000]

In [23]:
data['augmented'] = np.nan

In [24]:
data

polarity                                              tweet  augmented
0             0  VERY SAD! MY BROTHER GOES BACK TO GERMANY TOMO...        NaN
1             0  Really sad I can't participate at the bike wee...        NaN
2             4                              @iamabhimanyu thanks         NaN
3             4  mando diao LIVE @rock am ring 09 so toll und d...        NaN
4             0          @n8lewis I wish that I could have helped         NaN
...         ...                                                ...        ...
49995         0  @astrid_sunrise Aw. I've been trying to convin...        NaN
49996         0  first admu-dlsu game on aug. 9 :| i have class...        NaN
49997         4  why must wake up so early. I need my sleeeeep....        NaN
49998         4                    Quiiierooo ver Up y Star Treck         NaN
49999         0  Getting my car fixed. I have to leave it overn...        NaN

[50000 rows x 3 columns]

In [25]:
from tqdm import tqdm
for i in tqdm(range(len(data))):
    data["augmented"][i] = easyAugmenter.augment(data["tweet"][i])[0]


  0%|          | 0/50000 [00:00<?, ?it/s]/home/maxwell/Thesis/restructure/venv_txtatck/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/maxwell/Thesis/restructure/venv_txtatck/lib/python3.7/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
100%|██████████| 50000/50000 [47:41<00:00, 17.47it/s]  


In [26]:
data.to_csv('augmented_sentiment140.csv',encoding='utf-8')

# CREATING THE PREDICTIONS

In [3]:
# !python3 -m venv venv_pysentimiento
!pip install pysentimiento
!pip install -U scikit-learn

You should consider upgrading via the '/home/maxwell/Thesis/restructure/venv_pysentimiento/bin/python3 -m pip install --upgrade pip' command.
  Using cached scikit_learn-1.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.8 MB)
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
  Using cached scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
You should consider upgrading via the '/home/maxwell/Thesis/restructure/venv_pysentimiento/bin/python3 -m pip install --upgrade pip' command.


In [4]:
from pysentimiento import create_analyzer
sentiment_analyzer = create_analyzer(task="sentiment", lang="en")

In [5]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [6]:
data = pd.read_csv("./Sentiment_Dataset/Sentiment140/Augmented/augmented_sentiment140.csv", encoding='utf-8')

In [7]:
data['predicted_polarity'] = np.nan
data['augmented_polarity'] = np.nan

In [8]:
data

Unnamed: 0  polarity  \
0               0         0   
1               1         0   
2               2         4   
3               3         4   
4               4         0   
...           ...       ...   
49995       49995         0   
49996       49996         0   
49997       49997         4   
49998       49998         4   
49999       49999         0   

                                                   tweet  \
0      VERY SAD! MY BROTHER GOES BACK TO GERMANY TOMO...   
1      Really sad I can't participate at the bike wee...   
2                                  @iamabhimanyu thanks    
3      mando diao LIVE @rock am ring 09 so toll und d...   
4              @n8lewis I wish that I could have helped    
...                                                  ...   
49995  @astrid_sunrise Aw. I've been trying to convin...   
49996  first admu-dlsu game on aug. 9 :| i have class...   
49997  why must wake up so early. I need my sleeeeep....   
49998                    Quiiierooo ver Up y Star Treck    
49999  Getting my car fixed. I have to leave it overn...   

                                               augmented  predicted_polarity  \
0      VERY MY! SAD BACK GOES BROTHER TO GERMANY TOMO...                 NaN   
1      Really sad really I can't HTTP participate wor...                 NaN   
2                                   @iamabhimanyu thank                  NaN   
3      mando diao LIVE @Rock rock am ring MA 09 caree...                 NaN   
4              @n8lewis that I wish could I have helped                  NaN   
...                                                  ...                 ...   
49995  @astrid_sunrise Aw. I've been examine to conve...                 NaN   
49996  maiden admu-dlsu gamey on aug. IX :| i have cl...                 NaN   
49997  why I so up wake shelby. must need my sleeeeep...                 NaN   
49998              Quiiierooo 5 astir y principal Treck                  NaN   
49999                      car fixed. have it overnight                  NaN   

       augmented_polarity  
0                     NaN  
1                     NaN  
2                     NaN  
3                     NaN  
4                     NaN  
...                   ...  
49995                 NaN  
49996                 NaN  
49997                 NaN  
49998                 NaN  
49999                 NaN  

[50000 rows x 6 columns]

In [9]:
for i in tqdm(range(len(data))):

    data['predicted_polarity'][i] = sentiment_analyzer.predict(data['tweet'][i]).output
    data['augmented_polarity'][i] = sentiment_analyzer.predict(data['augmented'][i]).output

  0%|          | 0/50000 [00:00<?, ?it/s]/home/maxwell/Thesis/restructure/venv_pysentimiento/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/maxwell/Thesis/restructure/venv_pysentimiento/lib/python3.7/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/home/maxwell/Thesis/restructure/venv_pysentimiento/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying t

In [10]:
data

Unnamed: 0  polarity  \
0               0         0   
1               1         0   
2               2         4   
3               3         4   
4               4         0   
...           ...       ...   
49995       49995         0   
49996       49996         0   
49997       49997         4   
49998       49998         4   
49999       49999         0   

                                                   tweet  \
0      VERY SAD! MY BROTHER GOES BACK TO GERMANY TOMO...   
1      Really sad I can't participate at the bike wee...   
2                                  @iamabhimanyu thanks    
3      mando diao LIVE @rock am ring 09 so toll und d...   
4              @n8lewis I wish that I could have helped    
...                                                  ...   
49995  @astrid_sunrise Aw. I've been trying to convin...   
49996  first admu-dlsu game on aug. 9 :| i have class...   
49997  why must wake up so early. I need my sleeeeep....   
49998                    Quiiierooo ver Up y Star Treck    
49999  Getting my car fixed. I have to leave it overn...   

                                               augmented predicted_polarity  \
0      VERY MY! SAD BACK GOES BROTHER TO GERMANY TOMO...                NEG   
1      Really sad really I can't HTTP participate wor...                NEG   
2                                   @iamabhimanyu thank                 POS   
3      mando diao LIVE @Rock rock am ring MA 09 caree...                NEU   
4              @n8lewis that I wish could I have helped                 POS   
...                                                  ...                ...   
49995  @astrid_sunrise Aw. I've been examine to conve...                NEG   
49996  maiden admu-dlsu gamey on aug. IX :| i have cl...                NEU   
49997  why I so up wake shelby. must need my sleeeeep...                NEG   
49998              Quiiierooo 5 astir y principal Treck                 NEU   
49999                      car fixed. have it overnight                 NEU   

      augmented_polarity  
0                    NEG  
1                    NEG  
2                    NEU  
3                    NEU  
4                    NEU  
...                  ...  
49995                NEU  
49996                NEU  
49997                NEU  
49998                NEU  
49999                NEU  

[50000 rows x 6 columns]

In [11]:
data.to_csv('./Sentiment_Dataset/Sentiment140/Augmented/predicted_sentiment140.csv', encoding='utf-8',index=False)

# EVALUATION

In [12]:
from sklearn.metrics import classification_report, confusion_matrix

In [15]:
data['polarity'].replace(0,'NEG', inplace=True)
data['polarity'].replace(2,'NEU', inplace=True)
data['polarity'].replace(4,'POS', inplace=True)

In [16]:
data

Unnamed: 0 polarity                                              tweet  \
0               0      NEG  VERY SAD! MY BROTHER GOES BACK TO GERMANY TOMO...   
1               1      NEG  Really sad I can't participate at the bike wee...   
2               2      POS                              @iamabhimanyu thanks    
3               3      POS  mando diao LIVE @rock am ring 09 so toll und d...   
4               4      NEG          @n8lewis I wish that I could have helped    
...           ...      ...                                                ...   
49995       49995      NEG  @astrid_sunrise Aw. I've been trying to convin...   
49996       49996      NEG  first admu-dlsu game on aug. 9 :| i have class...   
49997       49997      POS  why must wake up so early. I need my sleeeeep....   
49998       49998      POS                    Quiiierooo ver Up y Star Treck    
49999       49999      NEG  Getting my car fixed. I have to leave it overn...   

                                               augmented predicted_polarity  \
0      VERY MY! SAD BACK GOES BROTHER TO GERMANY TOMO...                NEG   
1      Really sad really I can't HTTP participate wor...                NEG   
2                                   @iamabhimanyu thank                 POS   
3      mando diao LIVE @Rock rock am ring MA 09 caree...                NEU   
4              @n8lewis that I wish could I have helped                 POS   
...                                                  ...                ...   
49995  @astrid_sunrise Aw. I've been examine to conve...                NEG   
49996  maiden admu-dlsu gamey on aug. IX :| i have cl...                NEU   
49997  why I so up wake shelby. must need my sleeeeep...                NEG   
49998              Quiiierooo 5 astir y principal Treck                 NEU   
49999                      car fixed. have it overnight                 NEU   

      augmented_polarity  
0                    NEG  
1                    NEG  
2                    NEU  
3                    NEU  
4                    NEU  
...                  ...  
49995                NEU  
49996                NEU  
49997                NEU  
49998                NEU  
49999                NEU  

[50000 rows x 6 columns]

In [22]:
print("REPORT")
print(classification_report(data['polarity'], data["predicted_polarity"], target_names=['NEG','NEU','POS']))

print("CONFUSSION MATRIX")
print(confusion_matrix(data['polarity'], data["predicted_polarity"]))


REPORT


/home/maxwell/Thesis/restructure/venv_pysentimiento/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/maxwell/Thesis/restructure/venv_pysentimiento/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/maxwell/Thesis/restructure/venv_pysentimiento/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

              precision    recall  f1-score   support

         NEG       0.88      0.55      0.68     25092
         NEU       0.00      0.00      0.00         0
         POS       0.78      0.62      0.69     24908

    accuracy                           0.58     50000
   macro avg       0.55      0.39      0.46     50000
weighted avg       0.83      0.58      0.68     50000

CONFUSSION MATRIX
[[13751  6959  4382]
 [    0     0     0]
 [ 1851  7657 15400]]


In [23]:
print("REPORT")
print(classification_report(data['polarity'], data["augmented_polarity"], target_names=['NEG','NEU','POS']))

print("CONFUSSION MATRIX")
print(confusion_matrix(data['polarity'], data["augmented_polarity"]))

REPORT


/home/maxwell/Thesis/restructure/venv_pysentimiento/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/maxwell/Thesis/restructure/venv_pysentimiento/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/maxwell/Thesis/restructure/venv_pysentimiento/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

              precision    recall  f1-score   support

         NEG       0.84      0.41      0.56     25092
         NEU       0.00      0.00      0.00         0
         POS       0.76      0.45      0.57     24908

    accuracy                           0.43     50000
   macro avg       0.53      0.29      0.37     50000
weighted avg       0.80      0.43      0.56     50000

CONFUSSION MATRIX
[[10408 11216  3468]
 [    0     0     0]
 [ 1977 11701 11230]]


In [24]:
set(data['polarity'])

{'NEG', 'POS'}