# CREAETING THE AUGMENTED DATASET

In [4]:
!rm -r venv_txtatck
!python3.7 -m venv venv_txtatck
!pip install textattack -q

In [5]:
from textattack.augmentation.recipes import EasyDataAugmenter
easyAugmenter = EasyDataAugmenter(pct_words_to_swap=0.5, transformations_per_example=1)

[nltk_data] Downloading package omw-1.4 to /home/maxwell/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [6]:
import pandas as pd
import numpy as np

In [9]:
data = pd.read_csv(
    'Sentiment_Dataset/SemEval17/Clean/semeval.csv', 
    encoding = 'utf-8'
)

In [10]:
data['augmented'] = np.nan

In [11]:
data

polarity                                               text  augmented
0          NEU  Picturehouse's, Pink Floyd's, 'Roger Waters: T...        NaN
1          NEU  Order Go Set a Watchman in store or through ou...        NaN
2          NEG  If these runway renovations at the airport pre...        NaN
3          NEU  If you could ask an onstage interview question...        NaN
4          POS  A portion of book sales from our Harper Lee/Go...        NaN
...        ...                                                ...        ...
20627      NEU  @ShaquilleHoNeal from what I think you're aski...        NaN
20628      POS  Iran ranks 1st in liver surgeries, Allah bless...        NaN
20629      NEU  Hours before he arrived in Saudi Arabia on Tue...        NaN
20630      NEG  @VanityFair  Alex Kim Kardashian worth how to ...        NaN
20631      NEU  I guess even Pandora knows Justin Bieber is a ...        NaN

[20632 rows x 3 columns]

In [13]:
from tqdm import tqdm
for i in tqdm(range(len(data))):
    data["augmented"][i] = easyAugmenter.augment(data["text"][i])[0]

  0%|          | 0/20632 [00:00<?, ?it/s]/tmp/ipykernel_36943/4289361308.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["augmented"][i] = easyAugmenter.augment(data["text"][i])[0]
100%|██████████| 20632/20632 [34:10<00:00, 10.06it/s]


In [16]:
data

polarity                                               text  \
0          NEU  Picturehouse's, Pink Floyd's, 'Roger Waters: T...   
1          NEU  Order Go Set a Watchman in store or through ou...   
2          NEG  If these runway renovations at the airport pre...   
3          NEU  If you could ask an onstage interview question...   
4          POS  A portion of book sales from our Harper Lee/Go...   
...        ...                                                ...   
20627      NEU  @ShaquilleHoNeal from what I think you're aski...   
20628      POS  Iran ranks 1st in liver surgeries, Allah bless...   
20629      NEU  Hours before he arrived in Saudi Arabia on Tue...   
20630      NEG  @VanityFair  Alex Kim Kardashian worth how to ...   
20631      NEU  I guess even Pandora knows Justin Bieber is a ...   

                                               augmented  
0      Picturehouse's,, 'Roger: The - opening 29 Sept...  
1      tell proceed countersink a watchman in stock o...  
2      If these rails restoration at the aerodrome fo...  
3               If ask an onstage Miss USA tomorrow, it?  
4      ampere dowry of Koran sales from our Harper le...  
...                                                  ...  
20627  @asking what from in Future no ShaquilleHoNeal...  
20628  Iran outrank ranks 1st first in liver surgerie...  
20629  Hours Tuesday he Arabia mercilessly Syria's in...  
20630  @VanityFair  Alex Kim Kardashian Worth how to ...  
20631  ace estimate still Pandora recognize Justin Bi...  

[20632 rows x 3 columns]

In [18]:
# !mkdir Sentiment_Dataset/SemEval17/Augmented
data.to_csv("./Sentiment_Dataset/SemEval17/Augmented/augmented_SemEval17.csv",encoding='utf-8')

# CREATING THE PREDICTIONS

In [20]:
# !python3 -m venv venv_pysentimiento
!pip install pysentimiento
!pip install -U scikit-learn

  Using cached torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl (887.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 9.2 MB/s eta 0:00:000:00:01m eta 0:00:01m
  Using cached emoji-1.7.0.tar.gz (175 kB)
  Preparing metadata (setup.py) ... done
  Using cached catalogue-2.0.8-py3-none-any.whl (17 kB)
  Using cached pydantic-1.10.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
  Using cached srsly-2.4.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (492 kB)
  Using cached pathy-0.10.1-py3-none-any.whl (48 kB)
  Using cached murmurhash-1.0.9-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (21 kB)
  Using cached typer-0.7.0-py3-none-any.whl (38 kB)
  Using cached preshed-3.0.8-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (124 kB)
  Using cached wasabi-1.1.1-py3-none-any.whl (27 kB)
  Using cached langcodes-3.3.0-py3-none-any.whl (181 kB)
  Usi

In [21]:
from pysentimiento import create_analyzer
sentiment_analyzer = create_analyzer(task="sentiment", lang="en")

In [22]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [23]:
data = pd.read_csv("Sentiment_Dataset/SemEval17/Augmented/augmented_SemEval17.csv", encoding='utf-8')

In [24]:
data['predicted_polarity'] = np.nan
data['augmented_polarity'] = np.nan

In [27]:
data

Unnamed: 0 polarity                                               text  \
0               0      NEU  Picturehouse's, Pink Floyd's, 'Roger Waters: T...   
1               1      NEU  Order Go Set a Watchman in store or through ou...   
2               2      NEG  If these runway renovations at the airport pre...   
3               3      NEU  If you could ask an onstage interview question...   
4               4      POS  A portion of book sales from our Harper Lee/Go...   
...           ...      ...                                                ...   
20627       20627      NEU  @ShaquilleHoNeal from what I think you're aski...   
20628       20628      POS  Iran ranks 1st in liver surgeries, Allah bless...   
20629       20629      NEU  Hours before he arrived in Saudi Arabia on Tue...   
20630       20630      NEG  @VanityFair  Alex Kim Kardashian worth how to ...   
20631       20631      NEU  I guess even Pandora knows Justin Bieber is a ...   

                                               augmented  predicted_polarity  \
0      Picturehouse's,, 'Roger: The - opening 29 Sept...                 NaN   
1      tell proceed countersink a watchman in stock o...                 NaN   
2      If these rails restoration at the aerodrome fo...                 NaN   
3               If ask an onstage Miss USA tomorrow, it?                 NaN   
4      ampere dowry of Koran sales from our Harper le...                 NaN   
...                                                  ...                 ...   
20627  @asking what from in Future no ShaquilleHoNeal...                 NaN   
20628  Iran outrank ranks 1st first in liver surgerie...                 NaN   
20629  Hours Tuesday he Arabia mercilessly Syria's in...                 NaN   
20630  @VanityFair  Alex Kim Kardashian Worth how to ...                 NaN   
20631  ace estimate still Pandora recognize Justin Bi...                 NaN   

       augmented_polarity  
0                     NaN  
1                     NaN  
2                     NaN  
3                     NaN  
4                     NaN  
...                   ...  
20627                 NaN  
20628                 NaN  
20629                 NaN  
20630                 NaN  
20631                 NaN  

[20632 rows x 6 columns]

In [28]:
for i in tqdm(range(len(data))):

    data['predicted_polarity'][i] = sentiment_analyzer.predict(data['text'][i]).output
    data['augmented_polarity'][i] = sentiment_analyzer.predict(data['augmented'][i]).output

  0%|          | 0/20632 [00:00<?, ?it/s]/tmp/ipykernel_36943/1327365210.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['predicted_polarity'][i] = sentiment_analyzer.predict(data['text'][i]).output
/tmp/ipykernel_36943/1327365210.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['augmented_polarity'][i] = sentiment_analyzer.predict(data['augmented'][i]).output
 13%|█▎        | 2728/20632 [03:03<20:05, 14.86it/s]


KeyboardInterrupt: 

In [11]:
data.to_csv('./Sentiment_Dataset/Sentiment140/Augmented/predicted_sentiment140.csv', encoding='utf-8',index=False)

# EVALUATION

In [12]:
from sklearn.metrics import classification_report, confusion_matrix

In [15]:
data['polarity'].replace(0,'NEG', inplace=True)
data['polarity'].replace(2,'NEU', inplace=True)
data['polarity'].replace(4,'POS', inplace=True)

In [16]:
data

Unnamed: 0 polarity                                              tweet  \
0               0      NEG  VERY SAD! MY BROTHER GOES BACK TO GERMANY TOMO...   
1               1      NEG  Really sad I can't participate at the bike wee...   
2               2      POS                              @iamabhimanyu thanks    
3               3      POS  mando diao LIVE @rock am ring 09 so toll und d...   
4               4      NEG          @n8lewis I wish that I could have helped    
...           ...      ...                                                ...   
49995       49995      NEG  @astrid_sunrise Aw. I've been trying to convin...   
49996       49996      NEG  first admu-dlsu game on aug. 9 :| i have class...   
49997       49997      POS  why must wake up so early. I need my sleeeeep....   
49998       49998      POS                    Quiiierooo ver Up y Star Treck    
49999       49999      NEG  Getting my car fixed. I have to leave it overn...   

                                               augmented predicted_polarity  \
0      VERY MY! SAD BACK GOES BROTHER TO GERMANY TOMO...                NEG   
1      Really sad really I can't HTTP participate wor...                NEG   
2                                   @iamabhimanyu thank                 POS   
3      mando diao LIVE @Rock rock am ring MA 09 caree...                NEU   
4              @n8lewis that I wish could I have helped                 POS   
...                                                  ...                ...   
49995  @astrid_sunrise Aw. I've been examine to conve...                NEG   
49996  maiden admu-dlsu gamey on aug. IX :| i have cl...                NEU   
49997  why I so up wake shelby. must need my sleeeeep...                NEG   
49998              Quiiierooo 5 astir y principal Treck                 NEU   
49999                      car fixed. have it overnight                 NEU   

      augmented_polarity  
0                    NEG  
1                    NEG  
2                    NEU  
3                    NEU  
4                    NEU  
...                  ...  
49995                NEU  
49996                NEU  
49997                NEU  
49998                NEU  
49999                NEU  

[50000 rows x 6 columns]

In [22]:
print("REPORT")
print(classification_report(data['polarity'], data["predicted_polarity"], target_names=['NEG','NEU','POS']))

print("CONFUSSION MATRIX")
print(confusion_matrix(data['polarity'], data["predicted_polarity"]))


REPORT


/home/maxwell/Thesis/restructure/venv_pysentimiento/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/maxwell/Thesis/restructure/venv_pysentimiento/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/maxwell/Thesis/restructure/venv_pysentimiento/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

              precision    recall  f1-score   support

         NEG       0.88      0.55      0.68     25092
         NEU       0.00      0.00      0.00         0
         POS       0.78      0.62      0.69     24908

    accuracy                           0.58     50000
   macro avg       0.55      0.39      0.46     50000
weighted avg       0.83      0.58      0.68     50000

CONFUSSION MATRIX
[[13751  6959  4382]
 [    0     0     0]
 [ 1851  7657 15400]]


In [23]:
print("REPORT")
print(classification_report(data['polarity'], data["augmented_polarity"], target_names=['NEG','NEU','POS']))

print("CONFUSSION MATRIX")
print(confusion_matrix(data['polarity'], data["augmented_polarity"]))

REPORT


/home/maxwell/Thesis/restructure/venv_pysentimiento/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/maxwell/Thesis/restructure/venv_pysentimiento/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/maxwell/Thesis/restructure/venv_pysentimiento/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

              precision    recall  f1-score   support

         NEG       0.84      0.41      0.56     25092
         NEU       0.00      0.00      0.00         0
         POS       0.76      0.45      0.57     24908

    accuracy                           0.43     50000
   macro avg       0.53      0.29      0.37     50000
weighted avg       0.80      0.43      0.56     50000

CONFUSSION MATRIX
[[10408 11216  3468]
 [    0     0     0]
 [ 1977 11701 11230]]


In [24]:
set(data['polarity'])

{'NEG', 'POS'}