# CREAETING THE AUGMENTED DATASET

In [4]:
# !rm -r venv_txtatck
# !python3.7 -m venv venv_txtatck
!pip install textattack -q

You should consider upgrading via the '/home/user/Desktop/sentimiento/sentimentalDestroR/venv_txtatck/bin/python3.7 -m pip install --upgrade pip' command.


In [5]:
from textattack.augmentation.recipes import EasyDataAugmenter
easyAugmenter = EasyDataAugmenter(pct_words_to_swap=0.2, transformations_per_example=1)

/home/user/Desktop/sentimiento/sentimentalDestroR/venv_txtatck/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[nltk_data] Downloading package omw-1.4 to /home/user/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [6]:
import pandas as pd
import numpy as np

In [7]:
data = pd.read_csv(
    'Sentiment_Dataset/SemEval17/Clean/semeval.csv', 
    encoding = 'utf-8'
)

In [8]:
data['augmented'] = np.nan

In [9]:
data

polarity                                               text  augmented
0          NEU  Picturehouse's, Pink Floyd's, 'Roger Waters: T...        NaN
1          NEU  Order Go Set a Watchman in store or through ou...        NaN
2          NEG  If these runway renovations at the airport pre...        NaN
3          NEU  If you could ask an onstage interview question...        NaN
4          POS  A portion of book sales from our Harper Lee/Go...        NaN
...        ...                                                ...        ...
20627      NEU  @ShaquilleHoNeal from what I think you're aski...        NaN
20628      POS  Iran ranks 1st in liver surgeries, Allah bless...        NaN
20629      NEU  Hours before he arrived in Saudi Arabia on Tue...        NaN
20630      NEG  @VanityFair  Alex Kim Kardashian worth how to ...        NaN
20631      NEU  I guess even Pandora knows Justin Bieber is a ...        NaN

[20632 rows x 3 columns]

In [10]:
from tqdm import tqdm
for i in tqdm(range(len(data))):
    data["augmented"][i] = easyAugmenter.augment(data["text"][i])[0]

  0%|          | 0/20632 [00:00<?, ?it/s]/home/user/Desktop/sentimiento/sentimentalDestroR/venv_txtatck/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/user/Desktop/sentimiento/sentimentalDestroR/venv_txtatck/lib/python3.7/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
100%|██████████| 20632/20632 [16:04<00:00, 21.39it/s]


In [11]:
data

polarity                                               text  \
0          NEU  Picturehouse's, Pink Floyd's, 'Roger Waters: T...   
1          NEU  Order Go Set a Watchman in store or through ou...   
2          NEG  If these runway renovations at the airport pre...   
3          NEU  If you could ask an onstage interview question...   
4          POS  A portion of book sales from our Harper Lee/Go...   
...        ...                                                ...   
20627      NEU  @ShaquilleHoNeal from what I think you're aski...   
20628      POS  Iran ranks 1st in liver surgeries, Allah bless...   
20629      NEU  Hours before he arrived in Saudi Arabia on Tue...   
20630      NEG  @VanityFair  Alex Kim Kardashian worth how to ...   
20631      NEU  I guess even Pandora knows Justin Bieber is a ...   

                                               augmented  
0      Picturehouse's, Pink Floyd's, 'Roger stone Wat...  
1      order Go placed a Watchman in store or through...  
2      If these runway renovations at the airport pre...  
3      If you could enquire an onstage interview wond...  
4      A parcel of book sales from our Harper Lee/fun...  
...                                                  ...  
20627  @ShaquilleHoNeal from what I conceive you're a...  
20628    Iran ranks 1st in surgeries, Allah the country.  
20629  Hours before he arrived in Saudi Arabia on, Tu...  
20630  @VanityFair  Alex Kardashian worth how love Ki...  
20631  I guess even knows Justin is a grown up... thi...  

[20632 rows x 3 columns]

In [12]:
# !mkdir Sentiment_Dataset/SemEval17/Augmented
data.to_csv("./Sentiment_Dataset/SemEval17/Augmented/augmented(20%)_SemEval17.csv",encoding='utf-8')

# CREATING THE PREDICTIONS

In [1]:
# !python3 -m venv venv_pysentimiento
!pip install pysentimiento
!pip install -U scikit-learn

  Using cached pysentimiento-0.4.2-py3-none-any.whl (30 kB)
  Using cached transformers-4.13.0-py3-none-any.whl (3.3 MB)
  Preparing metadata (setup.py) ... done
  Using cached torch-1.13.1-cp37-cp37m-manylinux1_x86_64.whl (887.5 MB)
  Using cached datasets-1.18.4-py3-none-any.whl (312 kB)
  Using cached emoji-1.7.0-py3-none-any.whl
  Using cached regex-2022.10.31-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (757 kB)
  Using cached filelock-3.11.0-py3-none-any.whl (10.0 kB)
  Using cached numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
  Using cached tokenizers-0.10.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (3.3 MB)
  Using cached sacremoses-0.0.53-py3-none-any.whl
  Using cached huggingface_hub-0.13.4-py3-none-any.whl (200 kB)
  Using cached importlib_metadata-6.3.0-py3-none-any.whl (22 kB)
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
  Using cached tqdm-4.65.0-py3-none-an

In [2]:
from pysentimiento import create_analyzer
sentiment_analyzer = create_analyzer(task="sentiment", lang="en")

/home/user/Desktop/sentimiento/sentimentalDestroR/venv_sentimiento/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [5]:
data = pd.read_csv("./Sentiment_Dataset/SemEval17/Augmented/augmented(20%)_SemEval17.csv",encoding='utf-8')

In [6]:
data['predicted_polarity'] = np.nan
data['augmented_polarity'] = np.nan

In [7]:
data

Unnamed: 0 polarity                                               text  \
0               0      NEU  Picturehouse's, Pink Floyd's, 'Roger Waters: T...   
1               1      NEU  Order Go Set a Watchman in store or through ou...   
2               2      NEG  If these runway renovations at the airport pre...   
3               3      NEU  If you could ask an onstage interview question...   
4               4      POS  A portion of book sales from our Harper Lee/Go...   
...           ...      ...                                                ...   
20627       20627      NEU  @ShaquilleHoNeal from what I think you're aski...   
20628       20628      POS  Iran ranks 1st in liver surgeries, Allah bless...   
20629       20629      NEU  Hours before he arrived in Saudi Arabia on Tue...   
20630       20630      NEG  @VanityFair  Alex Kim Kardashian worth how to ...   
20631       20631      NEU  I guess even Pandora knows Justin Bieber is a ...   

                                               augmented  predicted_polarity  \
0      Picturehouse's, Pink Floyd's, 'Roger stone Wat...                 NaN   
1      order Go placed a Watchman in store or through...                 NaN   
2      If these runway renovations at the airport pre...                 NaN   
3      If you could enquire an onstage interview wond...                 NaN   
4      A parcel of book sales from our Harper Lee/fun...                 NaN   
...                                                  ...                 ...   
20627  @ShaquilleHoNeal from what I conceive you're a...                 NaN   
20628    Iran ranks 1st in surgeries, Allah the country.                 NaN   
20629  Hours before he arrived in Saudi Arabia on, Tu...                 NaN   
20630  @VanityFair  Alex Kardashian worth how love Ki...                 NaN   
20631  I guess even knows Justin is a grown up... thi...                 NaN   

       augmented_polarity  
0                     NaN  
1                     NaN  
2                     NaN  
3                     NaN  
4                     NaN  
...                   ...  
20627                 NaN  
20628                 NaN  
20629                 NaN  
20630                 NaN  
20631                 NaN  

[20632 rows x 6 columns]

In [8]:
for i in tqdm(range(len(data))):

    data['predicted_polarity'][i] = sentiment_analyzer.predict(data['text'][i]).output
    data['augmented_polarity'][i] = sentiment_analyzer.predict(data['augmented'][i]).output

  0%|          | 0/20632 [00:00<?, ?it/s]/home/user/Desktop/sentimiento/sentimentalDestroR/venv_sentimiento/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/user/Desktop/sentimiento/sentimentalDestroR/venv_sentimiento/lib/python3.7/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/home/user/Desktop/sentimiento/sentimentalDestroR/venv_sentimiento/lib/python3.7/site-packages/ipykernel_launcher.py:4:

In [9]:
data.to_csv('./Sentiment_Dataset/SemEval17/Augmented/predicted(20%)_semeval17.csv', encoding='utf-8',index=False)

# EVALUATION

In [10]:
from sklearn.metrics import classification_report, confusion_matrix

In [11]:
data

Unnamed: 0 polarity                                               text  \
0               0      NEU  Picturehouse's, Pink Floyd's, 'Roger Waters: T...   
1               1      NEU  Order Go Set a Watchman in store or through ou...   
2               2      NEG  If these runway renovations at the airport pre...   
3               3      NEU  If you could ask an onstage interview question...   
4               4      POS  A portion of book sales from our Harper Lee/Go...   
...           ...      ...                                                ...   
20627       20627      NEU  @ShaquilleHoNeal from what I think you're aski...   
20628       20628      POS  Iran ranks 1st in liver surgeries, Allah bless...   
20629       20629      NEU  Hours before he arrived in Saudi Arabia on Tue...   
20630       20630      NEG  @VanityFair  Alex Kim Kardashian worth how to ...   
20631       20631      NEU  I guess even Pandora knows Justin Bieber is a ...   

                                               augmented predicted_polarity  \
0      Picturehouse's, Pink Floyd's, 'Roger stone Wat...                NEU   
1      order Go placed a Watchman in store or through...                NEU   
2      If these runway renovations at the airport pre...                NEG   
3      If you could enquire an onstage interview wond...                NEU   
4      A parcel of book sales from our Harper Lee/fun...                POS   
...                                                  ...                ...   
20627  @ShaquilleHoNeal from what I conceive you're a...                NEU   
20628    Iran ranks 1st in surgeries, Allah the country.                POS   
20629  Hours before he arrived in Saudi Arabia on, Tu...                NEG   
20630  @VanityFair  Alex Kardashian worth how love Ki...                NEG   
20631  I guess even knows Justin is a grown up... thi...                NEG   

      augmented_polarity  
0                    NEU  
1                    NEU  
2                    NEG  
3                    NEU  
4                    POS  
...                  ...  
20627                NEU  
20628                POS  
20629                NEU  
20630                NEG  
20631                NEU  

[20632 rows x 6 columns]

In [12]:
print("REPORT")
print(classification_report(data['polarity'], data["predicted_polarity"], target_names=['NEG','NEU','POS']))

print("CONFUSSION MATRIX")
print(confusion_matrix(data['polarity'], data["predicted_polarity"]))


REPORT
              precision    recall  f1-score   support

         NEG       0.79      0.88      0.83      3231
         NEU       0.88      0.82      0.85     10342
         POS       0.84      0.88      0.86      7059

    accuracy                           0.85     20632
   macro avg       0.84      0.86      0.85     20632
weighted avg       0.85      0.85      0.85     20632

CONFUSSION MATRIX
[[2839  373   19]
 [ 699 8480 1163]
 [  34  805 6220]]


In [13]:
print("REPORT")
print(classification_report(data['polarity'], data["augmented_polarity"], target_names=['NEG','NEU','POS']))

print("CONFUSSION MATRIX")
print(confusion_matrix(data['polarity'], data["augmented_polarity"]))

REPORT
              precision    recall  f1-score   support

         NEG       0.73      0.76      0.75      3231
         NEU       0.79      0.83      0.81     10342
         POS       0.84      0.76      0.80      7059

    accuracy                           0.80     20632
   macro avg       0.79      0.78      0.79     20632
weighted avg       0.80      0.80      0.80     20632

CONFUSSION MATRIX
[[2465  709   57]
 [ 798 8560  984]
 [  93 1571 5395]]
